/* **** The fundamental basic-skeleton is generated by QGIS **** */
/* **** Leaflet **** */

// Overlay layers (TMS)
var lyr = L.tileLayer('./{z}/{x}/{y}.png', {tms: true, opacity: 1, attribution: '&copy; <a href="https://www.cottbus.de/verwaltung/gb_iv/stadtentwicklung/">Stadtentwicklung Cottbus</a>, 05/2022, <a href="https://stadtentwicklung.github.io/masterplan/"><b>DEUTSCH</b></a>, <a href="https://stadtentwicklung.github.io/masterplan-english/"><b>ENGLISH</b></a>, <a href="https://stadtentwicklung.github.io/masterplan-polski/"><b>POLSKI</b></a>', minZoom: 10, maxZoom: 15});

// Map
var map = L.map('map', {
    center: [51.78179619043856, 14.430890490667228],
    //zoom: 15,
    minZoom: 10,
    maxZoom: 15,
    layers: lyr,
	loadingControl: true
});

// Title
var title = L.control();
title.onAdd = function(map) {
    this._div = L.DomUtil.create('div', 'ctl title');
    this.update();
    return this._div;
};

title.update = function(props) {
    this._div.innerHTML = "Masterowy plan Chó¶ebuskego pódzajt¹nego jasora 3.0";
};
title.addTo(map);

// Fit to overlay bounds (SW and NE points with (lat, lon))
map.fitBounds([[51.72837123461897, 14.552784241190125], [51.83522114625816, 14.30899674014433]]);
		
// Geolocating		
function onLocationFound(e) {
    var location = e.latlng
    L.marker(location).addTo(map).bindPopup("Sy nì¼i how.").openPopup();
};

function onLocationError(e) {
	alert(e.message);
};

function getLocationLeaflet() {
	map.on('locationfound', onLocationFound);
	map.on('locationerror', onLocationError);
	map.locate({setView: true, maxZoom: 15});
};
		
// Custom project-marker
var redIcon = new L.Icon({
	iconUrl: 'https://raw.githubusercontent.com/pointhi/leaflet-color-markers/master/img/marker-icon-2x-red.png',
	shadowUrl: 'https://cdnjs.cloudflare.com/ajax/libs/leaflet/0.7.7/images/marker-shadow.png',
	iconSize: [25, 41],
	iconAnchor: [12, 41],
	popupAnchor: [1, -34],
	shadowSize: [41, 41]
});

//1
L.marker([51.77727, 14.39582], {icon: redIcon}).addTo(map).bindPopup("<p><strong>1. P¶istawowy kwartìr Chó¶ebuz</strong></p><p>Z p¶istawowym kwartìrom bu¼o Chó¶ebuz &bdquo;mìsto p¶i wó¼e&rdquo;. Na kóñcu jazoroweje wósy nastanjo mjazy p¶ibrjogom Chó¶ebuskego pódzajt¹nego jazora a B168 nowy inowatiwny kwartìr z promenadu, mìsæañskim p¶istawom a z nì¼i 200 wustawad³owymi mìstnami za co³ny. Pódla ¹yrokego wobceàka wódnego sporta, sportowego a strowotniskego centruma, bydlenjow, wobchodow, gósæeñcow ako teke hotelowego a zarìdowañskego kompleksa nastanjo &bdquo;Forum £u¾yca/Carboneum&rdquo; - informaciski centrum za wótmìnjate zwiski mjazy kulturnymi stawiznami, p¶irodnym rumom a wudobywanim brunice w regionje. P¶istawowy kwartìr dej ako prìdny kwartìr w Chó¶ebuzu wótpowìdowa¶ pominanju CO&#8322;-neutralnego wuwi¶a mìsta. Zachopinajucy p¶i planowaju, wubìranju materiala a konstrukcije,  p¶ez inowatiwnu koncepciju mobility a¾ k CO&#8322;-neutralnemu zastaranju z energiju dej p¶istawowy kwartìr staja¶ za ce³u Nimsku mìritka za trajne a za klimu p¶igódne urbane wuwi¶e.</p>");
//2
L.marker([51.77004, 14.37917], {icon: redIcon}).addTo(map).bindPopup("<p><strong>2. Jazorowe p¶edmìsto</strong></p><p>Mìstotwaàske zwìzanje centruma mìsta a Chó¶ebuskego pódzajt¹nego jazora jo jaden z nejwa¾njej¹ych projektow w p¶iducych lìt¼asetkach a inicial CO&#8322;-neutralnego a klimarezistentnego wuwi¶a Chó¶ebuza. Jìdro togo zwìzanja jo nìgaj¹na zeleznicowa cera Chó¶ebuz-Gubin, kótara¾ jo by³a wót 2000 p¶ez brunicu obsoletna. How dej nasta¶ urbany zeleny lichy rum za pì¹karjow, kólasarjow a zjawny wósobowy wobchad do bliskosæi. Wusmìrjenje mìsæañskego terena k wó¼e bu¼o p¶i tom flankìrowane p¶ez wuwi¶e jazorowego p¶edmìsta póspóromje teje zwìzujuceje wósy. How nastanjo rum p¶ichoda ako moderny, urbany a trajny mìsæañski kwartìr a roz¹yrna zelena p¶estrìñ. Planowanja p¶edwi¼e nowe bydleñske wobceàki, atraktiwne ¼ì³aàstwowe grunty, inowatiwny energijowy campus ako myslaàsku fabriku a teke kub³añski a zastojnstwowy centrum ze ¼ì³owymi mìstnami w bogatej licbje. Nowe funkcije a wugótowañske kwality w zmysle zasadnego procesa p¶etwari mìsta a inowatiwny zjawny wobchad do bliskosæi definìruju wupominanja na p¶iduce wuwi¶e mìsta na chó¶ebuskem pódzajt¹u.</p>");
//3
L.marker([51.78746, 14.38042], {icon: redIcon}).addTo(map).bindPopup("<p><strong>3. ®ylowk</strong></p><p>Na d³ujkem wjacorje, w direktnem susedstwje z p¶istawowym kwartìrom nastanu bydleñske wobtwarjenja ako wudopo³njenje k sedli¹æowemu wobceàkoju ®ylowka z lìp¹ynu bliskosæi k mìstoju a wó¼e. How deje nasta¶ bydlenja w modernej architektoniskej rìcy a z pominanim CO&#8322;-neutralnego wuwi¶a mìsta. Flankìrowany bu¼o kwartìr p¶ez ¾ylowkojski p¶ibrjog, la¾ko p¶istupny pó kólasu abo pì¹y p¶ede w¹ym za mìsæañskich gósæi, ken¾ k¶ì se kupa¶.</p>");
//4
L.marker([51.7975, 14.38316], {icon: redIcon}).addTo(map).bindPopup("<p><strong>4. £akoma - Rogozno</strong></p><p>Nìgaj¹na wjas £akoma jo centralne k¶icni¹æo p¶i jazorje za kólasowarjow mjazy  jazoroweju sæa¾ku nawoko³o a (nad)regionalnymi kólasowaàskimi sæa¾kami resp. nawopak. P¶ed pódwjacornym p¶ibrjogom Chó¶ebuskego pódzajt¹nego jazora dej nasta¶ plìjuca kupa z gósæeñcom a ferijowym bydlenim. P¶iro¼e p¶ewóstajony wótrìzk p¶ibrjoga z p¶ibrjozneju dro¾ku wabi k wuchój¼owanju p¶i jazorje direktnje p¶i wó¼e. Na pódpo³noc wót £akomeje rozp¶estrìwa se rogozañski p¶ibrjog, kótary¾ se wubìrnje gó¼i za gósæi z lokalneje wokoliny, ken¾ k¶ì se kupa¶,  ale teke za kólasaàskich turistow póspóromje sæa¾ki nawoko³o.</p>");
//5
L.marker([51.80482, 14.42282], {icon: redIcon}).addTo(map).bindPopup("<p><strong>5. P¶istaw Gatojce</strong></p><p>Na pódpo³dnjowej k¹omje wejsnego ¼ìla Nowa Wjas gmejny Gatojce nastanjo &bdquo;jazorowy p¶istaw&ldquo;. Planuju natwari¶ p¶istaw za sportowe co³ny na jadnab 16.000 m&sup2; wódneje p¶estrìni za 100 wustawad³owych mìstnow. Ko³owoko³o p¶iducego p¶istawowego basenka  nastanjo p¶istawowy kwartìr z promenadu p¶i jazorje, bitujuceju rozglìd  na p¶istaw a pódzajt¹ny jazor. Promenada p¶izamknjo se na pódzajt¹u &bdquo;jazorowej wósy&ldquo; a wje¼o dalej k wustawad³oju za pasa¾ìrske ³o¼ownistwo a k &bdquo;rozwjaseleñskemu parkoju&ldquo;. P¶i promena¼e su wobceàki za mórske ¼ì³aàstwo, gastronomiju a p¶enocowañske mó¾nosæi. Wu¹ej togo su w p¶istawowem kwartìrje zaplanowane wobceàki za wobgóspodarjenje p¶istawa, ¼ì³aànju, sk³adowani¹æo co³now a  ferijowe bydlenja a domy. Twaàski teren za bydleñske domy p¶inosujo k wó¾ywjenju kwartìra wob ce³e lìto.</p>");
//6
L.marker([51.80745, 14.44994], {icon: redIcon}).addTo(map).bindPopup("<p><strong>6. Barbucka wu¹yna</strong></p><p>Barbucka wu¹yna jo kum¹tna wu¹yna, kótara¾ la¾y jadnab 30 m wu¹ej p¶irodneje wokoliny. Groma¼e z rozwjaseleñskim parkom &bdquo;Gatojce&ldquo; a rozglìdowañskim tormom jo wóna srjej¼i¹æo turistiskich póbitowanjow na pódpo³nocnem jazorowem brjogu. W rozwjaseleñskem parku su wu¹ej lì¶ojskego sañkowani¹æa teke zipline parcours, lìzeñska ska³a, b³u¼i¹æo, &bdquo;S³owjañski gaj bogow&ldquo; a &bdquo;sæa¾ka ma³ych bogow&ldquo;. Rozglìdowañski torm zmó¾nijo ¹yroki wuglìd na p¶ichodny jazor.</p>");
//7
L.marker([51.79691, 14.44921], {icon: redIcon}).addTo(map).bindPopup("<p><strong>7. Barbucki zalew</strong></p><p>Barbucki zalew se idealnje gó¼i za wìcej zogolowate muzikowe zarìdowanja, ¼iwad³owe gra¶a a¾ k wjelikim abo priwatnym zarìdowanjam. Wu¹ej togo jo wón surfpoint p¶i jazorje. Wódna p¶estrìñ a p¶ibrjog w zalewje bitujotej z wusmìrjenim na pódpo³dnjo nejlìp¹e wumìnjenja za kite surfowarjow. Sezonowa gastronomija, póbitowanja za rozwucowanje surfowanja a wupó¾ycanje ale teke ³uka za stanowanje, mìstno k wótstajenju bydleñskich mobilow a wjelike sportni¹æo deje p¶i pominanju CO&#8322;-neutralnego twarjenja a ¹onujucego wobchadanja z ressourcami bitowa¶ ako planowañsku premisu rum za trajny, aktiwny turizm wódnego sporta.</p>");
//8
L.marker([51.78252, 14.47835], {icon: redIcon}).addTo(map).bindPopup("<p><strong>8. Energijowy centrum</strong></p><p>Na nìgaj¹nych brunicowych za³o¾kach brunicoweje wótwórjoneje jamy nastanjo góspodaàstwowy wobceàk za industriju a producìrujuce ¼ì³aàstwo z fokusom na regeneratiwne energije a na wobbìgowe góspodarjowanje. Pód wobchadym aspektom derje wótwórjony ¼ì³aàstwowy teren dej se wutwari¶ na centrum technologije a  za³o¾aàski centrum energijow do p¶ichoda (¶ì¾y¹æo  dorostujuce surowizny, alternatiwne dobywanje energije) na ce³kownej p³oninje 55 ha.</p>");
//9
L.marker([51.78239, 14.4593], {icon: redIcon}).addTo(map).bindPopup("<p><strong>9. Energijowa krajina</strong></p><p>Na pódzajt¹u jazora, mjazy sæa¾ku nawoko³o a energijowym centrumom, nara¼iju zelenu energijowu krajinu. ¦ì¾y¹æo dej by¶ w p¶icho¼e produkcija regeneratiwnych energijow w wobjadnosæi z p¶ewa¾nje gólnistwowym a p¶iro¼e bliskim naslìdnym wu¾ywanim  krajiny pó zakóñcenju wudobywanja brunice. Za³o¾ki za p¶etwórjenje wìt¹oweje a s³yñcneje energije na milinu symbolizìruju how zmìnu energijowego zastaranja.  Woglìdarje mógu na informaciskich toflach póspóromje sæa¾ki nawoko³o se informìrowa¶ wó stawiznach dobywanja energije.</p>");
//10
L.marker([51.75012, 14.48234], {icon: redIcon}).addTo(map).bindPopup("<p><strong>10. Klincañski jazor</strong></p><p>Klincañski jazor zmìjo z natwarjenim a zachowanim gódnotnych p¶irodnych a krajinowych arealow a z wuwi¶im p¶iro¼e bliskego turizma wósebny wuznam. Ze swójim wuformowanim gó¼i se za profesionelnu regatowu ceru 2.5000 do 3.000 m. &bdquo;Wjas³owañski sportowy centrum&ldquo; zjadno¶ijo póbitowanje za wódny sport w p¶icho¼e kradu centralnje a wjele sportowych towaristwow by je móga³o wu¾ywa¶. Ze spi¶istupnjenim jazora dejmy na zak³a¼e prognosticìrowanego zakóñcenja napo³njowanja z wódu licy¶ radnje pó dogótowanju Chó¶ebuskego pódzajt¹nego jazora.</p>");
//11
L.marker([51.74994, 14.44685], {icon: redIcon}).addTo(map).bindPopup("<p><strong>11. P¶irodny pódpo³dnjowy p¶ibrjog</strong></p><p>Wu¹ego po³o¾enja dla jo ten areal wizuelne zwìzanje mjazy Klincañskim jazorom a Chó¶ebuskim pódzajt¹nym jazorom. How dej na cerje jadnab 250 m nasta¶ p¶irodny jazorowy p¶ibrjog za p¶ija¶elow nudizma a kupanja z wjelikeju pótrjebu za p¶irodu. Intensiwne wu¾ywanje wólnego casa a turizma njejo dla togo p¶edwi¼one. P¶ibrjog jo p¶istupny pì¹y abo pó kólasu póspóromje sæa¾ki nawoko³o.</p>");
//12
L.marker([51.75482, 14.41677], {icon: redIcon}).addTo(map).bindPopup("<p><strong>12. Wuwijañski rum ©lichow-pódpo³dnjo</strong></p><p>Na pódpo³dnju jsy ©lichow twóri kum¹tnje natwarjona, wótmìnjata krajina zachopk krajiny pìskowych zmìtow póspóromje  krotkowjacornego brjoga. Na wjelikich p¶estrìnjach jo how mó¾ne wu¾ywanje lichego casa a sportowanje, kótare¾ se maka z wejsnym charakterom wokoliny a rownocasnje zagórjujo p¶edew¹ym wótpócynka pótrjebnych a z p¶irodu zwìzanych wulìtarjow a tam bydlecych lu¼i.</p>");
//13
L.marker([51.76131, 14.41381], {icon: redIcon}).addTo(map).bindPopup("<p><strong>13. ©lichow</strong></p><p>©lichow la¾y direktnje p¶i p¶ichodnem Chó¶ebuskem pódzajt¹nem jazorje. How nastanjo p¶idatna bydleñska p¶estrìñ p¶ez wudopo³njenje a wu¾ywanje  proznych flakow wobydlonych mìstnow. Z wugótowanim najsy ako ¹arnìr mjazy sedli¹æom a ³o¼owym wustawad³om p¶i jazorje nastanjo nowy centrum jsy. Póspóromje najsy planuju chrom za w¹ake wu¾ywanje, p¶idrozny gósæeñc a serwis za kólasarjow, lodowañske stacije za e-bike a teke hy¹æi góspodu za kólasowarjow. P¶ez zastajenje wudobywanja brunice obsoletny w swójej funkciji ¹æitny nasyp p¶ed zogolom dej se na zak³a¼e wótpowìdnych konceptow p¶egótowa¶.</p>");
//14
L.marker([51.75772, 14.42844], {icon: redIcon}).addTo(map).bindPopup("<p><strong>14. ©lichow pódpo³dnjo</strong></p><p>Na krotkem zajt¹u ©lichowa dej na zak³a¼e kwalitow togo mìstna nasta¶ ma³y ale wósebny  dowolaàski centrum za sport a wellness. Teke swójski hotelowy p¶ibrjog a stupnik stej mó¾nej. P¶ibrjog jo za pì¹karjow a kólasarjow p¶istupny. Sportowe co³ny a  jich suwani¹æa how pak ¾edne njebudu, te su ga p¶edwi¼one jano w wobyma wustawad³oma p¶i jazorje.</p>");
//15
L.marker([51.76935, 14.40325], {icon: redIcon}).addTo(map).bindPopup("<p><strong>15. Chó¶ebuski p¶ibrjog</strong></p><p>Mjazy mìsæañskim p¶istawom a ©lichowom nastanjo z jadnab 18 ha g³owny jazorowy p¶ibrjog z regionalnym wuznamom. Pódla kupañskego p¶ibrjoga a sportowych mó¾nosæow wusoku kwalitu p¶ebywanja bituju teke mó¾nosæi za spódobne wusednjenje, p¶ewoblekanje, zastarañske póbitowanja, sanitarne za³o¾ki a wupó¾ycaànje la¾ad³ow, p¶es³yñcnikow abo co³now. Na p¶ibrjog derje p¶i¼o¹ pó sæa¾ce nawoko³o pì¹y, pó kólasu abo skate a pó B168 ze zjawnym wósobowym wobchadom do bliskosæi abo wósobowym awtom. Rowno tak za planowane wu¾ywanje ako teke za susedny p¶istawowy kwartìr wobstoj CO&#8322;-neutralna twaàska wa¹nja a ressource ¹onujuce wobgóspodarjenje.</p>");
//16
L.marker([51.74297, 14.36965], {icon: redIcon}).addTo(map).bindPopup("<p><strong>16. Grodowy park Rogeñc</strong></p><p>Krajina ko³owoko³o ¹lichojskeje wu¹yny dej se zwìza¶ z rogeñskeju parkoweju a kulturneju krajinu. Jìdro togo zwìzanja jo historiska Kastanijowa aleja, nìga knìski dojìzd ku grodoju a parkoju w Rogeñcu, ako sæa¾ka za pì¹ych a kólasarjow. Tema wugótowanje krajiny dej se wu¾ywa¶ ako znamje atraktiwnosæi za Chó¶ebuski pódzajt¹ny jazor. Rogeñski park jo historiska kulturna krajina, Chó¶ebuski pódzajt¹ny jazor jeje moderna interpretacija.</p>");
//17
L.marker([51.76085, 14.462], {icon: redIcon}).addTo(map).bindPopup("<p><strong>17. Sæa¾ka nawoko³o</strong></p><p>Woko³o Chó¶ebuskego pódzajt¹nego jazora nastanjo 27 m d³ujka sæa¾ka nawoko³o za drogowarjow, kólasowarjow, skaterow a joggowarjow. To¶ ta &bdquo;sæa¾ka nawoko³o Pódzajt¹nego jazora&ldquo; zap¶imjejo se do bramborskeje se¶i kólasowego wobchada a do ju¾o wobstojecych regionalnych sæa¾kow za kólasowanje. Sæa¾ka zwìzujo jadnotliwe mìstna, projekty, p¶ibrjogi a hotele p¶i Chó¶ebuskem pódzajt¹nem jazorje. Wuznam teje sæa¾ki nawoko³o dej se pokaza¶ p¶ez wjelgin atraktiwne wuformowanje krajiny, glìdajucy rowno tak na meblìrowanje (na p¶. ³awki, informaciske tofle na wópócywañskich stacijach atd.) ako teke we pówjerchowem wugótowanju.</p>");
//18
L.marker([51.7752, 14.44389], {icon: redIcon}).addTo(map).bindPopup("<p><strong>18. Li¹kojski zalew</strong></p><p>Bogaty na zalewach pódzajt¹ny brjog Chó¶ebuskego pódzajt¹nego jazora jo ze swójimi p¶ed nimi la¾ecymi kupami abo po³kupami póstajony za p¶iro¼e p¶ewóstajone, ¹æitane wuwi¶e flory a fawny. Nasta¶e kupy za pta¹ki z wobglìdowañskim mósæikom  dej se na tom mìstnje do statka staji¶.</p>");
//19
L.marker([51.74677, 14.45994], {icon: redIcon}).addTo(map).bindPopup("<p><strong>19. Jazorowa sæa¾ka za kólasowarjow</strong></p><p>P¶epo³o¾enje Sæa¾ki wjercha Pücklera za kólasowarjow dej zwìzowa¶ Chó¶ebuski pódzajt¹ny jazor z Klincañskim jazorom a na ten part sp¶istupni¶ nowo nastawajucu jazorinu za aktiwny, bliski p¶iro¼e a CO&#8322;-neutralny kólasowaàski a drogowañski turizm. Za to su sebje ju¾o myslili na wót rowniny njewótwisne p¶eprìcenja B97 a cery nìgaj¹neje jamoweje zeleznice.</p>");
//20
L.marker([51.78125, 14.42406], {icon: redIcon}).addTo(map).bindPopup("<p><strong>20. Jazorowe znamje</strong></p><p>Markantne znamje - jazor - dej by¶ rowno tak magnet za wócy a nosaà naglìdnosæi ako teke widobne znamje strukturneje zmìny. Mìstno zrazom markìrujo srjej¼ Chó¶ebuskego pódzajt¹nego jazora. Za namakanje idejow su na BTU Chó¶ebuz-Z³y Komorow p¶ewjadli studentske wubì¼owanje. Nejlìp¹e ideje p¶ed³ogow zap¶imjejotej mìsæañske zastojnstwo Chó¶ebuz a management pódzajt¹nego jazora do dal¹nego planowanja Chó¶ebuskego pódzajt¹nego jazora a pruwujotej jich realizaciju.</p>");
//21
L.marker([51.76595, 14.40668], {icon: redIcon}).addTo(map).bindPopup("<p><strong>21. Sportowy t¶iro¾k Chó¶ebuski pódzajt¹ny jazor</strong></p><p>W wob³uku realizacije projekta strukturnego wuwi¶a &bdquo;BMX event- a treningowy centrum w parku za sport a wólny cas Chó¶ebuski pódzajt¹ny jazor&ldquo; deje se w pódpo³dnjowem wobceàku Chó¶ebuskego pódzajt¹nego jazora na wusokosæi mìsæañskego ¼ìla De¹ank etablìrowa¶ nowe wu¾ywañske mó¾nosæi za sport a wólny cas a sp¶istupni¶ nowo wugótowany p¶ez p¶irodu pregowany mìsæañski rum p¶i wó¼e. Park na fry¹nem powìt¹u  ze sportowymi póbitowanjami na kraju a mjeñ¹ymi twaàskimi za³o¾kami (wc, zastojnstwo, kafejownja) ako pódrìdowane wu¾ywanje jo mó¾ny. Za wurìdny sport, sport we wólnem casu, masowy a towaristwowy sport by ze &bdquo;sportowym t¶iro¾kom&ldquo; z mìsæañskego p¶istawa, BMX-centruma/parka za sport a wólny cas a sportowego parka na fry¹nem powìt¹u stojali  wjelerake póbitowanja k dispoziciji.</p>");
//22
L.marker([51.75496, 14.39642], {icon: redIcon}).addTo(map).bindPopup("<p><strong>22. BUGA 2033 - wizija</strong></p><p>W Chó¶ebuzu jo se po³pìta lìt pó zjadno¶enju Nimskeje wótmì³o prìdne zwìzkowe zagrodnistwowe rozpokazowanje w nowych zwìzkowych krajach. Skóro styri lìt¼asetki pózd¼ej co Chó¶ebuz by¶ zasej gósæinaà a woglìdarjam z Nimskeje a Europy prezentìrowa¶ trajne wuwi¶e centruma nìgaj¹nego regiona wótwórjonych jamow. BUGA-koncept, kótary¾ wulicujo wótmìnjate stawizny mìsta a regiona, njejo dotychmìst hy¹æi ¾ednje eksistìrowa³: Mjazy centrumom mìsta, Rogeñskim parkom a Chó¶ebuskim pódzajt¹nym jazorom deje se we wjelerakich do¾ywjeñskich mó¾nosæach a na drogowañskich sæa¾kach p¶ibli¾y¶ kulturne stawizny we sple¶enju pomìrow p¶irody, techniki, góspodaàstwa, towari¹nosæi, wudobywanja brunice, energijoweje produkcije, znicenja krajiny a zgubjenja p¶irodnych ¾ywjeñskich zak³adow a pytanja lu¼i za swójeju identitu.</p>");